### ISSUE TITLE
Stop working after March 24th?

### ISSUE THREAD

**Issue by heitortsergent** [watson-developer-cloud/your-celebrity-match#1]
@germanattanasio really interesting application! I followed the link on adding more profiles, and found this message:

IMPORTANT: The beta User Modeling service is now the generally available Personality Insights service, effective February 24, 2015. See the Bluemix pricing page for information about pricing plans for generally available services.
Applications that use the User Modeling REST API will continue to function until March 24, 2015, when the beta User Modeling service will be retired. However, effective February 24, no new applications can be created that use the beta User Modeling service.
Please see the documentation for the Personality Insights service for information about using its REST API and for information about converting User Modeling applications to use the Personality Insights service.

Is this demo going to stop working after March 24?

**Comment by herchu** [comment]
Only the _beta_ version of the service will be discontinued, just in favor of the official API. 
The Celebrity Match (and any other application using the initial service) will need to be migrated to the new service -- which is just a formal step: unbind the old service, bind an instance of the new one. If no deprecated features were in use (see the official docs) then there will be no code updates required for applications to continue running.

**Comment by heitortsergent** [comment]
@herchu I see, and I just saw you guys also have a free plan ;). Thanks for the quick response!
