### ISSUE TITLE
"node app.js" does not properly start server locally

### ISSUE THREAD

**Issue by austntatious** [watson-developer-cloud/your-celebrity-match#68]
when running the app locally, the program hangs at the end of the app.js file, with 
`connect-to-mongo`
as the last console.log, instead of throwing any errors

**Comment by kognate** [comment]
Are you able to connect to the mongo server on your local host?

**Comment by austntatious** [comment]
yes, the mongo connection completes okay, but from what I see, it seems like starting the app with `node app.js` may cause an issue, since the `server.listen` command is in the server.js file. so the app starts, but it doesn't ever load the web server or start listening for requests

**Comment by austntatious** [comment]
Oh I see, the package.json shows that `npm start` will run `node server.js` The README should be updated accordingly, since it is still instructing us to run `node app.js`

**Comment by jzhang300** [comment]
Good catch, I just updated the readme to say `npm start` instead.
