### ISSUE TITLE
Sample application deployment tracking: repository URL is missing

### ISSUE THREAD

**Issue by ptitzler** [watson-developer-cloud/your-celebrity-match#72]
Hello!

It appears that the application is using the Sample application deployment tracking library `cf-deployment-tracker-client`(https://github.com/watson-developer-cloud/your-celebrity-match/blob/master/server.js#L5) but doesn't specify the [`repository` property in `package.json`](https://docs.npmjs.com/files/package.json#repository). Without this property no traceback information to your github repository is recorded. Please consider adding the following to `package.json`

```
    ...
    "dependencies": {
        ...   
       "cf-deployment-tracker-client": "*"
    },
    ...
   "repository": {
     "type": "git",
     "url": "https://github.com/watson-developer-cloud/your-celebrity-match.git"
   }
```

as shown in this example:  https://github.com/IBM-Bluemix/node-helloworld/blob/master/package.json#L9-18

**Comment by germanattanasio** [comment]
thanks @ptitzler
