### ISSUE TITLE
Failed to add celebrities even set the demo environment to 0 in bluemix.

### ISSUE THREAD

**Issue by ibmalan** [watson-developer-cloud/your-celebrity-match#73]
I used  button "deploy to bluemix" to deploy the sample to bluemix, then added credentials for mongodb, personality insights service and twitter API, then set the demo environment value from 1 to 0, but the application doesn't work.
when @germanatt from application dashboard, it will the below error.
Sorry, there was an error. Please try again later.

Is there anything I missed?

---

error logs:

App/0
instance 0
2016-08-26T17:48:18.321+0800
App/0
username: germanatt
2016-08-26T17:48:18.485+0800
App/0
germanatt is not a celebrity, lets see if is in the DB
2016-08-26T17:48:18.521+0800
App/0
germanatt found in the database
2016-08-26T17:48:18.558+0800
App/0
catch(): [TypeError: Cannot read property 'distance' of undefined]
2016-08-26T17:48:18.558+0800
App/0
done()
2016-08-26T17:48:18.560+0800
RTR/3
yourcelebritymatch-kaihong-1456.mybluemix.net - [26/08/2016:09:48:18.313 +0000] "GET /like/@germanatt HTTP/1.1" 500 0 6397 "https://yourcelebritymatch-kaihong-1456.mybluemix.net/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0" 108.168.250.154:13620 x_forwarded_for:"158.85.175.87" x_forwarded_proto:"https" vcap_request_id:929ab2d7-0211-4440-6c23-0fa42d543fd8 response_time:0.246524097 app_id:1b5b264e-9388-4840-9ea6-8aca84d2b76b x_global_transaction_id:"1593667457"
2016-08-26T17:48:18.560+0800
App/0
germanatt to be compared to: 0 celebrities

**Comment by ibmalan** [comment]
STG/0
2016-08-26T15:35:45.347+0800
App/0
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2016-08-26T15:36:23.197+0800
STG/0
2016-08-26T16:01:13.066+0800
App/0
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2016-08-26T16:01:42.046+0800
STG/0
2016-08-26T16:10:53.992+0800
App/0
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2016-08-26T16:11:31.167+0800
STG/0
2016-08-26T17:21:36.991+0800
App/0
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2016-08-26T17:22:15.197+0800
App/0
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2016-08-26T17:36:22.207+0800
STG/0
2016-08-26T17:40:36.418+0800
App/0
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
2016-08-26T17:41:09.393+0800

**Comment by germanattanasio** [comment]
Update the database with the celebrities by making a POST request to:

http://localhost:3000/celebrities/syncdb

**Comment by ibmalan** [comment]
I'm running the application on bluemix, not locally, so I update the database by making a POST request to: https://yourcelebritymatch-kaihong-1456.mybluemix.net/celebrities/syncdb instead of http://localhost:3000/celebrities/syncdb

but it seems not work. the celebrities database is still null.
[root@nsj1 ~]# curl -X POST https://yourcelebritymatch-kaihong-1456.mybluemix.net/celebrities/syncdb
[root@nsj1 ~]# 
[root@nsj1 ~]#

**Comment by germanattanasio** [comment]
The DEMO variable needs to be `0`

```
curl -v -X POST https://yourcelebritymatch-kaihong-1456.mybluemix.net/celebrities/syncdb -data=''
*   Trying 169.54.245.69...
* Connected to yourcelebritymatch-kaihong-1456.mybluemix.net (169.54.245.69) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.mybluemix.net
* Server certificate: DigiCert SHA2 Secure Server CA
* Server certificate: DigiCert Global Root CA
> POST /celebrities/syncdb HTTP/1.1
> Host: yourcelebritymatch-kaihong-1456.mybluemix.net
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 4
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 403 Forbidden
< X-Backside-Transport: FAIL FAIL
< Connection: Keep-Alive
< Transfer-Encoding: chunked
< Content-Type: application/json; charset=utf-8
< Date: Mon, 29 Aug 2016 02:27:48 GMT
< Etag: W/"5f-n1ZOmcYSHpztvh5HnpqCuQ"
< Strict-Transport-Security: max-age=86400
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: ALLOW-FROM https://ibm-sxsw.mybluemix.net
< X-Xss-Protection: 1; mode=block
< X-Global-Transaction-ID: 702890081
<
* Connection #0 to host yourcelebritymatch-kaihong-1456.mybluemix.net left intact
{"code":403,"error":"POST requests to /celebrities/ are forbidden","url":"/celebrities/syncdb"}
```

As you can see the app is saying that POSTs requests to `/celebrities/syncdb` are forbidden.

**Comment by germanattanasio** [comment]
Run:

``` sh
cf se yourcelebritymatch-kaihong-1456 DEMO 0
cf restage yourcelebritymatch-kaihong-1456
```

**Comment by ibmalan** [comment]
it works after executing those two commands by using cf cli, why the demo parameter doesn't take effect when set its value from bluemix dashboard? 
application yourcelebritymatch-kaihong-1456 -->Runtime-->Environment Variables-->DEMO from 1 to 0.(the only difference is no restage.)

**Comment by ibmalan** [comment]
I think we'd better to update the README guide about how to set DEMO.

**Comment by germanattanasio** [comment]
updated readme feaf8fa

**Comment by mctosimaitb** [comment]
i got error when adding celebrities

Oops!
404 Not Found
Requested page not found!
URL: /celebrities/add/@brunomars
Take me home

my url : https://ganeshacelebmatch.mybluemix.net
i already syncdb by typing https://ganeshacelebmatch.mybluemix.net/celebrities/syncdb and also resulting error.

demo mode already set to 0 from command line



```
App/0error: { code: 404, error: 'Not Found', url: '/celebrities/syncdb' }Dec 12, 2016 1:17:11 PM
RTR/0ganeshacelebmatch.mybluemix.net - [12/12/2016:06:17:11.709 +0000] "GET /celebrities/syncdb HTTP/1.1" 404 0 2069 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36" 169.54.202.27:10727 x_forwarded_for:"202.80.212.120" x_forwarded_proto:"https" vcap_request_id:61e34e8f-a9ff-46cf-7dc4-f96dc54624b2 response_time:0.004821422 app_id:20636130-7662-4a27-890a-5b9780b28c56 x_global_transaction_id:"932163985" Dec 12, 2016 1:17:11 PM
RTR/1ganeshacelebmatch.mybluemix.net - [12/12/2016:06:17:12.790 +0000] "GET /css/base.css HTTP/1.1" 304 0 0 "https://ganeshacelebmatch.mybluemix.net/celebrities/syncdb" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36" 169.54.202.28:29584 x_forwarded_for:"202.80.212.120" x_forwarded_proto:"https" vcap_request_id:6873781f-075c-4c66-5c52-c84ee5aaa05d response_time:0.013187984 app_id:20636130-7662-4a27-890a-5b9780b28c56 x_global_transaction_id:"2729382711"
```

**Comment by germanattanasio** [comment]
You are doing a GET but it should be a POST

**Comment by mctosimaitb** [comment]
how to set an url to be POST ?
Sorry, newbie here. @germanattanasio

**Comment by nfriedly** [comment]
if you have [curl](https://curl.haxx.se/) installed, you can run a command like this:

`curl -X POST "https://ganeshacelebmatch.mybluemix.net/celebrities/syncdb"`

Or you could write a node.js script to do it - https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by mctosimaitb** [comment]
still got 0 celebrities.
i already installing curl and do the command.
need your advice guys @germanattanasio @nfriedly 

> C:\Users\mctosima>curl -v -X POST "https://ganeshacelebmatch.mybluemix.net/celebrities/add/@brunomars"
```
* timeout on name lookup is not supported
*   Trying 158.85.156.19...
* TCP_NODELAY set
* Connected to ganeshacelebmatch.mybluemix.net (158.85.156.19) port 443 (#0)
* schannel: SSL/TLS connection with ganeshacelebmatch.mybluemix.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 208 bytes...
* schannel: sent initial handshake data: sent 208 bytes
* schannel: SSL/TLS connection with ganeshacelebmatch.mybluemix.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with ganeshacelebmatch.mybluemix.net port 443 (step 2/3)
* schannel: encrypted data buffer: offset 3005 length 4096
* schannel: sending next handshake data: sending 158 bytes...
* schannel: SSL/TLS connection with ganeshacelebmatch.mybluemix.net port 443 (step 2/3)
* schannel: encrypted data buffer: offset 51 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with ganeshacelebmatch.mybluemix.net port 443 (step 3/3)
* schannel: stored credential handle in session cache
> POST /celebrities/add/@brunomars HTTP/1.1
> Host: ganeshacelebmatch.mybluemix.net
> User-Agent: curl/7.51.0
> Accept: */*
>
* schannel: client wants to read 16384 bytes
* schannel: encdata_buffer resized 17408
* schannel: encrypted data buffer: offset 0 length 17408
* schannel: encrypted data got 158
* schannel: encrypted data buffer: offset 158 length 17408
* schannel: decrypted data length: 98
* schannel: decrypted data added: 98
* schannel: decrypted data cached: offset 98 length 16384
* schannel: encrypted data length: 31
* schannel: encrypted data cached: offset 31 length 17408
* schannel: server closed the connection
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 98
* schannel: decrypted data buffer: offset 0 length 16384
< HTTP/1.1 411 Error
< X-Backside-Transport: FAIL FAIL
< Content-Type: text/xml
< Connection: close
<
* schannel: client wants to read 16384 bytes
* schannel: server indicated shutdown in a prior call
* schannel: schannel_recv cleanup
* Curl_http_done: called premature == 0
* Closing connection 0
* schannel: shutting down SSL/TLS connection with ganeshacelebmatch.mybluemix.net port 443
* schannel: clear security context handle
```

**Comment by mctosimaitb** [comment]
Finally i can do POST to add celebrities...



One last question German, i'm little bit confused about the results. I dont understand how the apps convert the probability output from personality insight becoma a comparison chart.

For example , the 'ease' results from Needs tab.
How do you get the results, whereas i cant find 'ease' probability on the mongoDB records ?

another example.
'easy going'

i cant find easy going probability on the database (personality insight output)

:) thanks before

@germanattanasio @nfriedly
