### ISSUE TITLE
Sorry, there was an error. Please try again later.

### ISSUE THREAD

**Issue by tpeg5stan** [watson-developer-cloud/your-celebrity-match#74]
I deployed the app on bluemix using the one-button-to-deploy, and whatever I type, I always get the error : "Sorry, there was an error. Please try again later."

I saw a closed issue with a similar problem. Do you know what can be the cause ?

Thanks in advance

**Comment by germanattanasio** [comment]
You need to setup a database and load the profiles on that database. did you do that ?

**Comment by tpeg5stan** [comment]
Excuse me if I do not understand, but this site : https://mongolab.com seems down for me, and I do not find the mongolab service on Bluemix.
Am I supposed to cope with this, use a similar service, etc. ?

**Comment by germanattanasio** [comment]
Try with https://mlab.com/
