### ISSUE TITLE
Question about Euclidean distance formula

### ISSUE THREAD

**Issue by prathamesh13** [watson-developer-cloud/your-celebrity-match#75]
Doesn't the Similarity function defined in similarity.js returns similarity percentage rather than Euclidean distance as described in the function description? Also the formula used to calculate the euclidean distance appears to be little different from the general form for n-dimensional space mentioned in wiki. 

    origin_traits.forEach(function(trait, i) {
         distance += Math.pow(trait.percentage - target_traits[i].percentage, 2);
    });
    var ret = 1 - (Math.sqrt(distance / origin_traits.length));

Why is distance divided by the number of traits here? Shouldn't this be:
 
    var ret = 1 - (Math.sqrt(distance));

where `Math.sqrt(distance)` represents Euclidean distance. 

Thanks

**Comment by nfriedly** [comment]
Hey sorry no one ever responded to this, I think the basic answer is "good question, I don't know". 

If you'd like to send a PR that updates the description to be more accurate, I'd be happy to merge it. 

I'm going to close this for now though.
