### ISSUE TITLE
404 Error when making a **POST** request to:      `http://localhost:3000/celebrities/syncdb`

### ISSUE THREAD

**Issue by maithuy** [watson-developer-cloud/your-celebrity-match#80]
I'm following the steps in the README. The step syncdb is not very clear, as when I load the url on the browsers, the app throws 404.

Update the database with the celebrities by making a **POST** request to:

    `http://localhost:3000/celebrities/syncdb`

    The celebrities are not added by default. Hence the above step is recommended. Refer #Celebrities section below for more information.
    When running in bluemix make sure the environment variable `DEMO` is set to `0`.

**Comment by g00dL00Ks** [comment]
I'm having this same issue. More specifics about how to make the POST request would be helpful

**Comment by nfriedly** [comment]
> when I load the url on the browsers, the app throws 404

You're probably not doing a POST if you're loading it in a browser. Try this:

    curl -X POST "http://localhost:3000/celebrities/syncdb"

**Comment by maithuy** [comment]
Thanks for your help. I was just wondering how to syncdb.
