### ISSUE TITLE
How to add 'not-qualify as a celebrity' twitter profile batch

### ISSUE THREAD

**Issue by maithuy** [watson-developer-cloud/your-celebrity-match#81]
I would like to add a batch of twitter profiles (that are not qualified as celebrities) though the POST request rather adding individual profile as demonstrated in the below example:

curl -X POST --user {username}:{password} \
--header "Content-Type: application/json" \
--header "Accept: text/csv" \
--data-binary "@{path_to_file}profile.json" \
--output profile.csv \
"https://gateway.watsonplatform.net/personality-insights/api/v3/profile?version=2016-10-20&consumption_preferences=true&raw_scores=true&csv_headers=true"

**Comment by nfriedly** [comment]
Go for it! :)

That's not really a bug, though, so I'm going to close this ticket.
