### ISSUE TITLE
curl -X POST "http://localhost:3000/celebrities/add/@username" for users are not qualified as celebrities

### ISSUE THREAD

**Issue by maithuy** [watson-developer-cloud/your-celebrity-match#82]
Can I issue this curl -X POST "http://localhost:3000/celebrities/add/@username" for users are not qualified as celebrities, ie. Can I reduce the requirements for a celebrity to add to our database? "Ensure this person is verified, has at least 10,000 followers, and has over 1,000 tweets." For example, can we do unverified, and 100 followers and 100 tweets.

**Comment by nfriedly** [comment]
Sure, just edit this line: https://github.com/watson-developer-cloud/your-celebrity-match/blob/master/app/routes/celebrities.js#L133

**Comment by maithuy** [comment]
Thanks for the details. I've edited the line with 100 and it still doesn't take it
{"success":false,"error":"User does not qualify as a celebrity"}

**Comment by germanattanasio** [comment]
@maithuy we do some validation before adding a profile as a celebrity. https://github.com/watson-developer-cloud/your-celebrity-match/blob/master/app/routes/celebrities.js#L130

**Comment by nfriedly** [comment]
I'm not sure... did you restart / push to bluemix after editing the file?

**Comment by maithuy** [comment]
Yes I did restart. I have this app running locally. I think it's the check !user.verified that needs to be edited.
