### ISSUE TITLE
Live demo broken?

### ISSUE THREAD

**Issue by 192933488S** [watson-developer-cloud/your-celebrity-match#86]
Hi,

link 

Live demo: http://your-celebrity-match.ng.bluemix.net/ 

leads to this:

404 Not Found: Requested route ('your-celebrity-match.ng.bluemix.net') does not exist.

Also this seems not to work anymore:

https://your-celebrity-match.mybluemix.net/like/@potus

leading to error.

Regards

**Comment by germanattanasio** [comment]
@mamoonraja ☝️

**Comment by mamoonraja** [comment]
Live Demo is working now. Looking into the second issue.

**Comment by 192933488S** [comment]
Hi,
thanks for responding to this issue, but I cannot see it working.

https://your-celebrity-match.ng.bluemix.net/like/@[Twittername]

Does not work for me. Do I need to be logged in to the cloud?

Have a good week

**Comment by mamoonraja** [comment]
You do not need to login to the cloud, try this: http://your-celebrity-match.ng.bluemix.net/ and then enter twitter username. 
We're working on the second issue you mentioned originally, one with loading error after you enter twitter username. Apologies for the inconvenience.

**Comment by germanattanasio** [comment]
It looks like we didn't have Twitter credentials, I added a `TWITTER` environment variable, bump some dependencies and fixed an issue with the Personality Insights url.
I also updated the images for all the celebrities as instructed in the README.

Sorry for the delay @ludwigschreier 
This will get fixed once #87 is merged
