### ISSUE TITLE
Deployment Instructions on Bluemix

### ISSUE THREAD

**Issue by sarielda** [watson-developer-cloud/your-celebrity-match#92]
Do you happen to have instructions on how to deploy the app on Bluemix (CF)? I tried with the current manifest.yml but I faced multiple issues.

**Comment by germanattanasio** [comment]
What are the issues that you faced @sarielda?

**Comment by sarielda** [comment]
Thanks for the response @germanattanasio. I deployed the app and populated my db with celebrity profiles. I'm getting an error through at similarity.js when I try to match a user

08:23:38.486 | at /home/vcap/app/app/util/util.js:73:19
08:23:38.486 | at similarity (/home/vcap/app/app/util/similarity.js:29:32)
08:23:38.486 | at Array.map (native)
08:23:38.486 | at getDiffProfiles (/home/vcap/app/app/routes/user.js:72:24)
08:23:38.486 | at /home/vcap/app/app/routes/user.js:170:29
08:23:38.486 | at Promise_then_fulfilled (/home/vcap/app/node_modules/q/q.js:766:44)
08:23:38.485 | id: '1139651',
08:23:38.485 | catch(): TypeError: Cannot read property 'children' of undefined

line 29 at similarity.js is 
```javascript
   origin_traits = origin.tree.children[type].children[0].children,
```
and it looks like the users PI json is not structured that way. Any thoughts?
